services:
  dbrest:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: po_db
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass
    ports:
      - "5425:5432"

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbrest:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8082:8080"
    depends_on:
      - dbrest
